
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.6.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.BookingScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  guestName: 'guestName',
  guestPhone: 'guestPhone',
  roomTypeId: 'roomTypeId',
  roomId: 'roomId',
  bookingTime: 'bookingTime',
  durationExpected: 'durationExpected',
  status: 'status',
  deposit: 'deposit',
  createdAt: 'createdAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  bookingId: 'bookingId',
  roomId: 'roomId',
  staffId: 'staffId',
  startTime: 'startTime',
  endTime: 'endTime',
  roomTotal: 'roomTotal',
  servicesTotal: 'servicesTotal',
  discount: 'discount',
  finalTotal: 'finalTotal',
  status: 'status'
};

exports.Prisma.InvoiceServiceScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  serviceId: 'serviceId',
  quantity: 'quantity',
  priceAtTime: 'priceAtTime',
  orderTime: 'orderTime'
};

exports.Prisma.ServiceCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  displayOrder: 'displayOrder',
  isActive: 'isActive'
};

exports.Prisma.ServiceScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  name: 'name',
  price: 'price',
  stockQuantity: 'stockQuantity',
  isActive: 'isActive'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phoneNumber: 'phoneNumber'
};

exports.Prisma.PurchaseOrderScalarFieldEnum = {
  id: 'id',
  supplierId: 'supplierId',
  staffId: 'staffId',
  totalAmount: 'totalAmount',
  orderDate: 'orderDate'
};

exports.Prisma.InventoryLogScalarFieldEnum = {
  id: 'id',
  serviceId: 'serviceId',
  changeType: 'changeType',
  quantityChanged: 'quantityChanged',
  referenceId: 'referenceId',
  createdAt: 'createdAt'
};

exports.Prisma.VoucherScalarFieldEnum = {
  id: 'id',
  code: 'code',
  discountType: 'discountType',
  discountValue: 'discountValue',
  minInvoiceAmount: 'minInvoiceAmount',
  validFrom: 'validFrom',
  validUntil: 'validUntil',
  usageLimit: 'usageLimit'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  bookingId: 'bookingId',
  amount: 'amount',
  paymentMethod: 'paymentMethod',
  paymentType: 'paymentType',
  transactionTime: 'transactionTime'
};

exports.Prisma.RoomTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  capacity: 'capacity',
  basePricePerHour: 'basePricePerHour',
  description: 'description'
};

exports.Prisma.RoomScalarFieldEnum = {
  id: 'id',
  roomTypeId: 'roomTypeId',
  roomNumber: 'roomNumber',
  status: 'status'
};

exports.Prisma.PriceRuleScalarFieldEnum = {
  id: 'id',
  roomTypeId: 'roomTypeId',
  dayOfWeek: 'dayOfWeek',
  startTime: 'startTime',
  endTime: 'endTime',
  pricePerHour: 'pricePerHour'
};

exports.Prisma.ShiftScalarFieldEnum = {
  id: 'id',
  staffId: 'staffId',
  startTime: 'startTime',
  endTime: 'endTime',
  startingCash: 'startingCash',
  endingCash: 'endingCash',
  expectedCash: 'expectedCash'
};

exports.Prisma.EquipmentScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  name: 'name',
  serialNumber: 'serialNumber',
  status: 'status'
};

exports.Prisma.MaintenanceLogScalarFieldEnum = {
  id: 'id',
  equipmentId: 'equipmentId',
  maintenanceDate: 'maintenanceDate',
  description: 'description',
  cost: 'cost'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  phoneNumber: 'phoneNumber',
  email: 'email',
  passwordHash: 'passwordHash',
  refreshToken: 'refreshToken',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.BookingStatus = exports.$Enums.BookingStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  ARRIVED: 'ARRIVED'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  UNPAID: 'UNPAID',
  PAID: 'PAID'
};

exports.InventoryChangeType = exports.$Enums.InventoryChangeType = {
  IMPORT: 'IMPORT',
  SALE: 'SALE',
  DAMAGE: 'DAMAGE'
};

exports.DiscountType = exports.$Enums.DiscountType = {
  PERCENT: 'PERCENT',
  FIXED_AMOUNT: 'FIXED_AMOUNT'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CARD: 'CARD',
  MOMO: 'MOMO'
};

exports.PaymentType = exports.$Enums.PaymentType = {
  DEPOSIT: 'DEPOSIT',
  FINAL_PAYMENT: 'FINAL_PAYMENT',
  REFUND: 'REFUND'
};

exports.RoomStatus = exports.$Enums.RoomStatus = {
  AVAILABLE: 'AVAILABLE',
  IN_USE: 'IN_USE',
  MAINTENANCE: 'MAINTENANCE'
};

exports.EquipmentStatus = exports.$Enums.EquipmentStatus = {
  ACTIVE: 'ACTIVE',
  REPAIRING: 'REPAIRING',
  BROKEN: 'BROKEN'
};

exports.Role = exports.$Enums.Role = {
  CUSTOMER: 'CUSTOMER',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN'
};

exports.Prisma.ModelName = {
  Booking: 'Booking',
  Invoice: 'Invoice',
  InvoiceService: 'InvoiceService',
  ServiceCategory: 'ServiceCategory',
  Service: 'Service',
  Supplier: 'Supplier',
  PurchaseOrder: 'PurchaseOrder',
  InventoryLog: 'InventoryLog',
  Voucher: 'Voucher',
  Payment: 'Payment',
  RoomType: 'RoomType',
  Room: 'Room',
  PriceRule: 'PriceRule',
  Shift: 'Shift',
  Equipment: 'Equipment',
  MaintenanceLog: 'MaintenanceLog',
  User: 'User'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
